apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-color-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-color-app
  template:
    metadata:
      labels:
        app: k8s-color-app   # corrigido para bater com o selector
    spec:
      containers:
      - name: k8s-color-app
        image: rodrigobellizzieri/k8s-color-app
        ports:
        - containerPort: 5000
        env:
        - name: BACKGROUND_COLOR
          valueFrom:
            secretKeyRef:
              name: k8s-color-secret
              key: background_color
        - name: FONT_COLOR
          valueFrom:
            secretKeyRef:
              name: k8s-color-secret
              key: font_color
