apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-color-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-secret
  template:
    metadata:
      labels:
        app: color-secret   # corrigido para bater com o selector
    spec:
      containers:
      - name: color-secret
        image: rodrigobellizzieri/k8s-color-app
        ports:
        - containerPort: 5000
        env:
        - name: BACKGROUND_COLOR
          valueFrom:
            secretKeyRef:
              name: color-secret
              key: BACKGROUND_COLOR
        - name: FONT_COLOR
          valueFrom:
            secretKeyRef:
              name: color-secret
              key: FONT_COLOR
